Repository ComposeGears/Tiamat, pull requests merged in 2025-03, with the labels that each got.

#136 Use latest stable supported AGP in IntelliJ IDEA
  gradle/libs.versions.toml
Labels: housekeeping

#125 Content transition api & predictive back example
  .editorconfig
  example/app/composeApp/src/androidMain/AndroidManifest.xml
  example/app/composeApp/src/androidMain/kotlin/composegears/tiamat/example/MainApplication.kt
  example/app/composeApp/src/desktopMain/kotlin/composegears/tiamat/example/main.kt
  example/app/composeApp/src/wasmJsMain/kotlin/composegears/tiamat/example/main.kt
  example/content/src/commonMain/kotlin/composegears/tiamat/example/content/App.kt
  example/content/src/commonMain/kotlin/composegears/tiamat/example/content/content/HomeScreen.kt
  example/content/src/commonMain/kotlin/composegears/tiamat/example/content/content/advanced/AdvSharedElementTransition.kt
  example/platform/build.gradle.kts
  example/platform/src/androidMain/kotlin/composegears/tiamat/example/platform/Platform.android.kt
  example/platform/src/androidMain/kotlin/composegears/tiamat/example/platform/PredictiveBack.android.kt
  example/platform/src/commonMain/kotlin/composegears/tiamat/example/platform/Platform.kt
  example/platform/src/commonMain/kotlin/composegears/tiamat/example/platform/PredictiveBack.kt
  example/platform/src/iosMain/kotlin/composegears/tiamat/example/platform/Platform.ios.kt
  example/platform/src/iosMain/kotlin/composegears/tiamat/example/platform/PredictiveBack.ios.kt
  example/platform/src/jvmMain/kotlin/composegears/tiamat/example/platform/Platform.jvm.kt
  example/platform/src/jvmMain/kotlin/composegears/tiamat/example/platform/PredictiveBack.jvm.kt
  example/platform/src/wasmJsMain/kotlin/composegears/tiamat/example/platform/Platform.wasmJs.kt
  example/platform/src/wasmJsMain/kotlin/composegears/tiamat/example/platform/PredictiveBack.wasmJs.kt
  example/ui-core/src/commonMain/kotlin/composegears/tiamat/example/ui/core/CoreComponents.kt
  tiamat-koin/build.gradle.kts
  tiamat/api/android/tiamat.api
  tiamat/api/jvm/tiamat.api
  tiamat/build.gradle.kts
  tiamat/src/androidMain/kotlin/com/composegears/tiamat/NavContentTransform.android.kt
  tiamat/src/commonMain/kotlin/com/composegears/tiamat/Compose.kt
  tiamat/src/commonMain/kotlin/com/composegears/tiamat/NavContentTransform.kt
  tiamat/src/commonMain/kotlin/com/composegears/tiamat/NavController.kt
  tiamat/src/commonMain/kotlin/com/composegears/tiamat/TransitionController.kt
  tiamat/src/iosMain/kotlin/com/composegears/tiamat/NavContentTransform.ios.kt
  tiamat/src/jvmMain/kotlin/com/composegears/tiamat/NavContentTransform.jvm.kt
  tiamat/src/wasmJsMain/kotlin/com/composegears/tiamat/NavContentTransform.wasmJs.kt
  tiamat/src/wasmJsMain/kotlin/com/composegears/tiamat/Platform.wasmJs.kt
Labels: enhancement

#139 Migrate CameraX platform sample to new architecture
  example/app/composeApp/src/androidMain/AndroidManifest.xml
  example/platform/build.gradle.kts
  example/platform/src/androidMain/AndroidManifest.xml
  example/platform/src/androidMain/kotlin/composegears/tiamat/example/platform/AndroidViewLifecycleScreen.kt
  example/platform/src/androidMain/kotlin/composegears/tiamat/example/platform/Platform.android.kt
Labels: housekeeping

#141 Fix TransitionController require conditions
  tiamat/src/commonMain/kotlin/com/composegears/tiamat/TransitionController.kt
Labels: bug

#142 Remove nodejs() in wasmJs, use browser() target
  example/content/build.gradle.kts
  example/extra/build.gradle.kts
  example/platform/build.gradle.kts
  example/ui-core/build.gradle.kts
  tiamat-koin/build.gradle.kts
  tiamat/build.gradle.kts
Labels: housekeeping, 1.5.0

#145 Add md link verify action
  .editorconfig
  .github/workflows/verify.yml
Labels: housekeeping
